version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=haraslub
      - MONGO_INITDB_ROOT_PASSWORD=password1234!
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
