version: '3'
services:
  nginx:
    ports:
      - '3000:80'
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=haraslub
      - MONGO_PASSWORD=password1234!
      - SESSION_SECRET=secret1234!!!

    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=haraslub
      - MONGO_INITDB_ROOT_PASSWORD=password1234!
